### ISSUE TITLE
请问后台管理怎么登陆？

### ISSUE THREAD

**Issue by XSX-Milan** [RojerAlone/shop#2]

**Comment by RojerAlone** [comment]
/admin/login，偷懒没做权限系统，用户名是admin的用户是管理员，普通用户不能登陆

**Comment by XSX-Milan** [comment]
嗯嗯，我发送邮件出了问题，看了一下rpushObject没把EventModel里的哈希表存进去。。。你有这个问题吗

**Comment by RojerAlone** [comment]
这是[ fastjson 的序列化机制原因](https://github.com/alibaba/fastjson/issues/1245)，把 Map 改为 public 的就可以了，原来用 protostuff 的时候没有这个问题。
