### ISSUE TITLE
初学者：关于EventConsumer这个类的疑问

### ISSUE THREAD

**Issue by soviet943** [RojerAlone/shop#4]
首先，非常感谢您对项目的分享，逛了好多ssm项目，感觉您写的项目非常新颖，功能特点也很丰富，涉及的知识面广，我跟着您的项目边做边学做了1个多月，在后面阶段碰到个问题

目录/shop-master/src/main/java/cn/cie/event/EventConsumer.java
下的afterPropertiesSet()的方法在tomcat启动加载项目的时候加载
其中
while(true) { //一直循环下去，直到超时报错，卡在这里了，没搞懂，这样不就一直陷入死循环了吗
     EventModel event = redisUtil.lpopObject(EventModel.EVENT_KEY, EventModel.class);
     if (event == null) {
                continue;
     }
     if (!handlers.containsKey(event.getEventType())) {
                logger.error("error event type");
                continue;
      }
      for (EventHandler handler : handlers.get(event.getEventType())) {
                threadPool.execute(new EventConsumerThread(handler, event));
      }
}

**Comment by RojerAlone** [comment]
报的什么错误？贴一下异常信息。或许是 redis 的错误，我对 redis 的使用只限于了解基本用法，这个 RedisUtil.class 写的很粗糙而且很可能有 bug。

**Comment by soviet943** [comment]
信息: Initializing Spring root WebApplicationContext:
这里卡了一段时间然后直接跳出框
Server Tomcat v9.0 Server at localhost was unable to start within 100 seconds. If the server requires more time, try increasing the timeout in the server editor.
我是把redis搭建在了远程的服务器上，用自己的电脑测试项目，redis正常运行，也能正常插入用户的token。

**Comment by RojerAlone** [comment]
应该就是我用 Spring 的这个接口有问题，以前是直接在这里起了一个线程，在新线程中执行获取事件，后来只顾着改用线程池，忘了考虑这个问题了，我等下更新下代码你再试试。

**Comment by soviet943** [comment]
哇，可以了，感谢大哥。

**Comment by RojerAlone** [comment]
不客气，也可以看看我的其他仓库，有问题欢迎指出。
