### ISSUE TITLE
缺少文件 

### ISSUE THREAD

**Issue by WHY0529** [RojerAlone/shop#6]
请问缺少文件  该如何导入

**Comment by RojerAlone** [comment]
缺少什么文件？

**Comment by WHY0529** [comment]
No projects are found to import

**Comment by RojerAlone** [comment]
这是个 maven 项目，我猜测你用的是 eclipse，你应该以 maven 项目的形式导入，如果你用的是 IDEA 则可以直接导入。

慕课网上有个 maven 的课程，花半个小时了解一下相关概念就OK了。

**Comment by WHY0529** [comment]
> 这是个maven 项目，我猜测你用的是eclipse，你应该以maven 项目的形式导入，如果你用的是IDEA 则可以直接导入。
> 
> 慕课网上有个maven 的课程，花半个小时了解一下相关概念就OK了。

  我也是在自学   谢谢您的讲解.

**Comment by RojerAlone** [comment]
时间太久记不太清了，你先运行起来看看，报什么错再解决
