### ISSUE TITLE
kind.jsp的一些问题

### ISSUE THREAD

**Issue by LlorandoLau** [RojerAlone/shop#7]
浏览分类里面的类别链接是在哪里加上的呀？

**Comment by RojerAlone** [comment]
请详细描述一下问题

**Comment by LlorandoLau** [comment]
如图，在jsp文件没有找到对应的代码段：
![default](https://user-images.githubusercontent.com/28216165/49219678-f6ac3300-f40e-11e8-9fdb-55fcf3584eaf.PNG)

![2](https://user-images.githubusercontent.com/28216165/49219739-29eec200-f40f-11e8-94d2-d819e3136026.PNG)

**Comment by RojerAlone** [comment]
/js/biaoqian.js
前端做的很糙，是我舍友做的，你可以重点关注下后端代码，或者可以看下 [这个项目](https://github.com/RojerAlone/ssms)

**Comment by LlorandoLau** [comment]
嗯。后端的项目结构和代码逻辑都很清晰。

**Comment by RojerAlone** [comment]
这个项目是一年多以前写的，用的 Spring MVC，还是有点乱，你可以看下我上面说的那个，用的 Spring Boot，前端项目是我同学写的，没有源码但是有编译过后的前端代码，配套的还有个移动端的 APP 但是我没有代码，看看后端还是可以的。

**Comment by LlorandoLau** [comment]
好的
